### ISSUE TITLE
some methods are still missing self arguments

### ISSUE THREAD

**Issue by Alloyed** [rm-code/love-atom#16]
namely, most getters seems to be missing it, because with no arguments presumably you don't notice that it isn't there in the first place.

I'm using it in lua-lsp instead of atom, but this causes issues from my perspective: a no-argument function probably isn't a method and making the distinction would be nice~

**Comment by pablomayobre** [comment]
As I said [here](https://github.com/rm-code/love-atom/issues/15#issuecomment-346279826) to me there should be no distinction between methods and functions.

Type methods are just functions that take a `self` argument which must be a `table/userdata` of the appropriate Type.

I don't see the error you are having, getters (as in `Font:getWidth()`) do take a `self` argument and that has been fixed in the latest version.

EDIT: Further clarified [here](https://github.com/Alloyed/lua-lsp/commit/3a060790bb2b43dfd2065faa79746f2af20d6e0e#commitcomment-25775548)

**Comment by rm-code** [comment]
Maybe I misunderstand, but do you mean that we should change the recommendations based on wether the user types in a `:` or a `.`?

```lua
-- _ is the cursor position:
img:getH_ --> love-atom: img:getHeight()

img.getH_ --> love-atom: img.getHeight( self )
```

**Comment by pablomayobre** [comment]
That's done by autocomplete-lua so no need to perform any changes in love-atom.

I believe @Alloyed comment [here](https://github.com/Alloyed/lua-lsp/commit/3a060790bb2b43dfd2065faa79746f2af20d6e0e#commitcomment-25775950) clarifies the situation some more.

I believe that the current love-atom should be fine. Of course I would love it if we can keep the compatibility with [lua-lsp](https://github.com/Alloyed/lua-lsp) high.
